// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const borderWidths = {
  huge: '0.5rem',
  extraLarge: '0.375rem',
  large: '0.25rem',
  medium: '0.125rem',
  small: '0.09375rem',
  normal: '0.0625rem'
}

module.exports = borderWidths
