// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontSizes = {
  mobileXl6: '3.5rem',
  mobileXl5: '3rem',
  mobileXl4: '2.5rem',
  mobileXl3: '2rem',
  mobileXl2: '1.5rem',
  mobileXl: '1rem',
  mobileLarge: '0.875rem',
  mobileMedium: '0.75rem',
  mobileNormal: '0.625rem',
  mobileSmall: '0.5625rem',
  mobileTiny: '0.5rem',
  xl6: '7.5rem',
  xl5: '6rem',
  xl4: '5rem',
  xl3: '4rem',
  xl2: '2.5rem',
  xl: '1.5rem',
  large: '1.125rem',
  medium: '1rem',
  normal: '0.75rem',
  small: '0.625rem',
  tiny: '0.5rem'
}

module.exports = fontSizes
