// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontFamilies = {
  heading: 'Anonymous Pro',
  stylized: 'OCR A Std',
  normal: 'Work Sans'
}

module.exports = fontFamilies
