// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const mediaQueries = {
  small: '640px',
  medium: '768px',
  large: '1024px',
  extraLarge: '1280px',
  huge: '1536px'
}

module.exports = mediaQueries
