// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const opacities = {
  10: 0.1,
  15: 0.15,
  20: 0.2,
  25: 0.25,
  40: 0.4,
  50: 0.5,
  60: 0.6,
  70: 0.7,
  80: 0.8,
  90: 0.9,
  opaque: 1,
  disabled: 0.6,
  '05': 0.05,
  '2half': 0.03,
  transparent: 0
}

module.exports = opacities
