// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const radii = {
  full: '625rem',
  huge: '1.5rem',
  extraLarge: '1rem',
  large: '0.75rem',
  rounded: '0.5rem',
  small: '0.25rem',
  tiny: '0.125rem',
  hard: '0rem'
}

module.exports = radii
