// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const spacing = {
  10: '2.5rem',
  12: '3rem',
  16: '4rem',
  20: '5rem',
  24: '6rem',
  32: '8rem',
  40: '10rem',
  48: '12rem',
  56: '14rem',
  64: '16rem',
  '001pixel': '0.0625rem',
  '00half': '0.125rem',
  '01': '0.25rem',
  '01half': '0.375rem',
  '02': '0.5rem',
  '02half': '0.625rem',
  '03': '0.75rem',
  '03half': '0.875rem',
  '04': '1rem',
  '05': '1.25rem',
  '06': '1.5rem',
  '08': '2rem'
}

module.exports = spacing
