// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const zIndices = {
  top: 100,
  focus: 10,
  highest: 3,
  higher: 2,
  high: 1,
  regular: 0,
  under: -1
}

module.exports = zIndices
